const CSS = `
.dshDoctorButton{display:flex;align-items:center;gap:10px;width:100%;min-height:36px;padding:8px 10px;border:0;border-radius:8px;background:transparent;color:inherit;font:inherit;cursor:pointer}.dshDoctorButton:hover{background:color-mix(in srgb,currentColor 8%,transparent)}.dshDoctorButton[data-wide=false]{justify-content:center;padding:8px}.dshDoctorStatus{width:8px;height:8px;border-radius:50%;background:#8b8b93;box-shadow:0 0 0 2px color-mix(in srgb,#8b8b93 20%,transparent)}.dshDoctorStatus[data-level=healthy]{background:#3fb950}.dshDoctorStatus[data-level=warning]{background:#d29922}.dshDoctorStatus[data-level=error]{background:#f85149}
.dshDoctorOverlay{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;pointer-events:auto}.dshDoctorMask{position:absolute;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(3px)}.dshDoctorPanel{position:relative;width:min(560px,calc(100vw - 32px));max-height:min(760px,calc(100vh - 32px));overflow:auto;border:1px solid color-mix(in srgb,currentColor 14%,transparent);border-radius:18px;background:var(--color-bg-elevated,#2b2b2e);color:var(--color-text,#f1f1f3);box-shadow:0 24px 80px rgba(0,0,0,.42);padding:22px}.dshDoctorPanelHeader{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.dshDoctorPanelHeader h2{font-size:20px;margin:0}.dshDoctorIconButton{display:grid;place-items:center;width:32px;height:32px;border:0;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.dshDoctorIconButton:hover{background:color-mix(in srgb,currentColor 9%,transparent)}
.dshDoctorHero{display:flex;gap:14px;align-items:flex-start;padding:16px;border-radius:14px;background:color-mix(in srgb,#4d6bfe 12%,transparent);border:1px solid color-mix(in srgb,#4d6bfe 35%,transparent)}.dshDoctorHeroIcon{display:grid;place-items:center;width:36px;height:36px;flex:none;border-radius:10px;background:#4d6bfe;color:white}.dshDoctorHero h3{margin:0 0 5px;font-size:16px}.dshDoctorHero p{margin:0;color:var(--color-text-secondary,#b8b8bd);font-size:13px;line-height:1.5}.dshDoctorCounts{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.dshDoctorBadge{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;font-size:12px;background:color-mix(in srgb,currentColor 8%,transparent)}.dshDoctorBadge[data-level=error]{color:#ff8b87}.dshDoctorBadge[data-level=warning]{color:#e5bd57}
.dshDoctorActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.dshDoctorPrimary,.dshDoctorSecondary,.dshDoctorDanger{min-height:38px;padding:0 15px;border-radius:9px;font:inherit;font-weight:600;cursor:pointer}.dshDoctorPrimary{border:1px solid #4d6bfe;background:#4d6bfe;color:#fff}.dshDoctorSecondary{border:1px solid color-mix(in srgb,currentColor 22%,transparent);background:transparent;color:inherit}.dshDoctorDanger{border:1px solid color-mix(in srgb,#f85149 55%,transparent);background:color-mix(in srgb,#f85149 12%,transparent);color:#ff9b98}.dshDoctorPrimary:disabled,.dshDoctorSecondary:disabled{opacity:.55;cursor:not-allowed}.dshDoctorProgress{margin-top:18px;padding:14px;border-radius:12px;background:color-mix(in srgb,currentColor 5%,transparent);font-size:13px}.dshDoctorProgress ol{margin:0;padding-left:20px}.dshDoctorProgress li{padding:3px 0;color:var(--color-text-secondary,#b8b8bd)}.dshDoctorProgress li[data-active=true]{color:inherit;font-weight:600}.dshDoctorError{margin-top:14px;padding:10px 12px;border-radius:9px;background:color-mix(in srgb,#f85149 12%,transparent);color:#ffaaa7;font-size:13px;word-break:break-word}
.dshDoctorSection{display:flex;flex-direction:column;gap:18px;max-width:820px;padding-bottom:32px}.dshDoctorSectionHeader{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.dshDoctorSectionHeader h2{margin:0 0 6px;font-size:20px}.dshDoctorSectionHeader p{margin:0;color:var(--color-text-secondary,#8f8f96);font-size:13px}.dshDoctorCard{padding:16px;border:1px solid color-mix(in srgb,currentColor 13%,transparent);border-radius:12px;background:color-mix(in srgb,currentColor 3%,transparent)}.dshDoctorCard h3{margin:0 0 12px;font-size:15px}.dshDoctorIssueList,.dshDoctorHistoryList{display:flex;flex-direction:column;gap:8px;margin:0;padding:0;list-style:none}.dshDoctorIssue{display:grid;grid-template-columns:10px 1fr;gap:10px;padding:10px;border-radius:9px;background:color-mix(in srgb,currentColor 5%,transparent)}.dshDoctorIssueDot{width:8px;height:8px;border-radius:50%;margin-top:5px;background:#8b8b93}.dshDoctorIssueDot[data-level=error]{background:#f85149}.dshDoctorIssueDot[data-level=warning]{background:#d29922}.dshDoctorIssue strong{display:block;font-size:13px}.dshDoctorIssue p{margin:3px 0 0;color:var(--color-text-secondary,#aaaab0);font-size:12px;line-height:1.45}.dshDoctorEmpty{color:var(--color-text-secondary,#8f8f96);font-size:13px}.dshDoctorHistoryRow{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid color-mix(in srgb,currentColor 8%,transparent);font-size:13px}.dshDoctorHistoryRow:last-child{border-bottom:0}
.dshDoctorBanner{display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;padding:10px 12px;border:1px solid color-mix(in srgb,#f85149 42%,transparent);border-radius:11px;background:color-mix(in srgb,#f85149 10%,var(--color-bg,#1f1f21));color:inherit}.dshDoctorBannerText{display:flex;align-items:center;gap:9px;font-size:13px}.dshDoctorBannerActions{display:flex;align-items:center;gap:6px}.dshDoctorBanner button{white-space:nowrap}.dshDoctorVisuallyHidden{position:absolute!important;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media (prefers-color-scheme:light){.dshDoctorPanel{background:#fff;color:#242428}.dshDoctorHero p,.dshDoctorSectionHeader p,.dshDoctorIssue p,.dshDoctorEmpty{color:#66676f}.dshDoctorBanner{background:#fff5f5}}
@media (max-width:600px){.dshDoctorPanel{padding:16px;border-radius:14px}.dshDoctorSectionHeader{flex-direction:column}.dshDoctorBanner{align-items:flex-start}.dshDoctorBannerActions{flex-direction:column;align-items:stretch}}
`

export function installDoctorStyles(): () => void {
  const id = 'dsh-doctor/styles'
  const existing = document.querySelector(`style[data-plugin-css="${id}"]`)
  if (existing !== null) return () => {}
  const style = document.createElement('style')
  style.dataset.plugin = 'dsh-doctor'
  style.dataset.pluginCss = id
  style.textContent = CSS
  document.head.appendChild(style)
  return () => style.remove()
}
